#This is a basic workflow to help you ger started with Actions

name: Docker

# Controls when the workflow will run
on:

  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  # branches: [ "main " ]
  # pull_request:
  # branches: [ "main " ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@3

      -  runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.MIRA_TOKEN }} | docker login -u ${{ secrets.MIRA_NAME }} --password-stdin

	- name: Build business-layer container
  uses: docker/build-push-action@v2
  with:
    load: true
    tags: my-project/base
    context: business
    file: business/Dockerfile

- name: Build service
  uses: docker/build-push-action@v2
  with:
    load: true
    tags: my-ecr-repo/service
    context: service
    file: service/Dockerfile

- name: push service
  run: |
    docker push my-ecr-repo/service

	- name: Build and push
 	  uses: docker/build-push-action@V2
	  with:
          context: .
   	    file: ./Dockerfile
          push: true
          tags: ${{ secrets.MIRA_NAME }}/homework:latest     
